### ISSUE TITLE
Link for TNILGloss is dead

### ISSUE THREAD

**Issue by edderiofer** [uakci/ithkuil.place#1]
As per the title. The link to TNILGloss on https://ithkuil.place/ links to a nonexistent repository; I believe the correct repository is https://github.com/Syst3ms/TNILGloss .

**Comment by este-rs** [comment]
Oh, thanks for letting me know. The correct link is actually https://github.com/ngoriyasjil/IthkuilGloss; as you can tell, I updated the username part of the link but not the repo name. So much for quality assurance.
