### ISSUE TITLE
Updates on TNIL documentation

### ISSUE THREAD

**Issue by omasanori** [uakci/ithkuil.place#3]
Apparently there are some updates on the official TNIL documents.

- Morphology: `New_Ithkuil_design_doc_v_1_1.pdf` Version 1.2, December 29, 2022
  SHA256: `ed3d186a0f3226900d08c8d4cd03b2511c8d295381e135f491a4d8ec6120ca14`
- Affixes: `affixes_v_1_0.pdf` Version 1.0, Dec. 30, 2022
  SHA256: `fdc94646b99ea0719cb05a48ae9a7f5724e088774089a3ae4d4cff33b27d09a8`
- Script: `Script_for_New_Ithkuil.pdf` Version 1.0, December 2022
  SHA256: `fecea494db9b7fae209265e3819966801fee1a1d0124dad7db24c5c31346ad57`

**Comment by este-rs** [comment]
Thanks for the heads-up. Of course we should preserve every version that gets posted to the site, be it with or without prior announcement from JQ.

I'll add those when I'm free later tonight.

**Comment by este-rs** [comment]
Oh, forget that last comment, I thought the version numbers hadn't been bumped.

Is `Script_for_New_Ithkuil.pdf` in fact a distinct file from the one currently available in the archive?

**Comment by omasanori** [comment]
> Is Script_for_New_Ithkuil.pdf in fact a distinct file from the one currently available in the archive?

Yes, there seem some minor changes.

**Comment by este-rs** [comment]
Two of the files you've named hash to different sha256 upon downloading from ithkuil.net:
* design doc `64654066914725954d3c0f416509b59ea99291cab18bc10c78ece4428d8ffbf5`
* affixes `da69f284de9cc9bc3a57561aeb3c5b12222076718328c186f6891ea60915b00f`

@omasanori, for the sake of archival completeness, could you provide me with the versions of the two documents that you hashed?

**Comment by omasanori** [comment]
@uakci OK, I will send you these files by email.

**Comment by omasanori** [comment]
I've sent them. Ping me if not delivered.

**Comment by este-rs** [comment]
All done and dusted – thanks for the valuable contribution :D
